### ISSUE TITLE
mapbox new acces token

### ISSUE THREAD

**Issue by Derryrover** [lizardsystem/flooding-lib#38]
We need to change the the mapbox acces token for the background layers.

See below pr:
https://github.com/lizardsystem/flooding-lib/pull/39

What url is this app running on?
If it is not on one of the lizard.net domains we may need to add it to the whitelisted urls in the mapbox-admin-dashboard.
Please notify Tom de Boer in that case.

This ticket is part of a bgger ticket to change all mapbox tokens for all our apps:
nens/threedi-live-site#476

**Comment by lexvand** [comment]
@arjanverkerk Can you assist Tom in applying this change?

**Comment by arjanverkerk** [comment]
Well I don't really know where to start

**Comment by arjanverkerk** [comment]
@remcogerlich wil wel helpen.

**Comment by Derryrover** [comment]
@remcogerlich 

Hi Remco,
Could you help me with the mapbox key for the flooding lib?
The deadline is 1 august. 
Please let me know if you are not going to make it.

kr Tom

**Comment by remcogerlich** [comment]
Fixed
